require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HkPublicHolidaysController do

  # This should return the minimal set of attributes required to create a valid
  # HkPublicHoliday. As you add validations to HkPublicHoliday, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all hk_public_holidays as @hk_public_holidays" do
      hk_public_holiday = HkPublicHoliday.create! valid_attributes
      get :index
      assigns(:hk_public_holidays).should eq([hk_public_holiday])
    end
  end

  describe "GET show" do
    it "assigns the requested hk_public_holiday as @hk_public_holiday" do
      hk_public_holiday = HkPublicHoliday.create! valid_attributes
      get :show, :id => hk_public_holiday.id.to_s
      assigns(:hk_public_holiday).should eq(hk_public_holiday)
    end
  end

  describe "GET new" do
    it "assigns a new hk_public_holiday as @hk_public_holiday" do
      get :new
      assigns(:hk_public_holiday).should be_a_new(HkPublicHoliday)
    end
  end

  describe "GET edit" do
    it "assigns the requested hk_public_holiday as @hk_public_holiday" do
      hk_public_holiday = HkPublicHoliday.create! valid_attributes
      get :edit, :id => hk_public_holiday.id.to_s
      assigns(:hk_public_holiday).should eq(hk_public_holiday)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HkPublicHoliday" do
        expect {
          post :create, :hk_public_holiday => valid_attributes
        }.to change(HkPublicHoliday, :count).by(1)
      end

      it "assigns a newly created hk_public_holiday as @hk_public_holiday" do
        post :create, :hk_public_holiday => valid_attributes
        assigns(:hk_public_holiday).should be_a(HkPublicHoliday)
        assigns(:hk_public_holiday).should be_persisted
      end

      it "redirects to the created hk_public_holiday" do
        post :create, :hk_public_holiday => valid_attributes
        response.should redirect_to(HkPublicHoliday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hk_public_holiday as @hk_public_holiday" do
        # Trigger the behavior that occurs when invalid params are submitted
        HkPublicHoliday.any_instance.stub(:save).and_return(false)
        post :create, :hk_public_holiday => {}
        assigns(:hk_public_holiday).should be_a_new(HkPublicHoliday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HkPublicHoliday.any_instance.stub(:save).and_return(false)
        post :create, :hk_public_holiday => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hk_public_holiday" do
        hk_public_holiday = HkPublicHoliday.create! valid_attributes
        # Assuming there are no other hk_public_holidays in the database, this
        # specifies that the HkPublicHoliday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HkPublicHoliday.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hk_public_holiday.id, :hk_public_holiday => {'these' => 'params'}
      end

      it "assigns the requested hk_public_holiday as @hk_public_holiday" do
        hk_public_holiday = HkPublicHoliday.create! valid_attributes
        put :update, :id => hk_public_holiday.id, :hk_public_holiday => valid_attributes
        assigns(:hk_public_holiday).should eq(hk_public_holiday)
      end

      it "redirects to the hk_public_holiday" do
        hk_public_holiday = HkPublicHoliday.create! valid_attributes
        put :update, :id => hk_public_holiday.id, :hk_public_holiday => valid_attributes
        response.should redirect_to(hk_public_holiday)
      end
    end

    describe "with invalid params" do
      it "assigns the hk_public_holiday as @hk_public_holiday" do
        hk_public_holiday = HkPublicHoliday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HkPublicHoliday.any_instance.stub(:save).and_return(false)
        put :update, :id => hk_public_holiday.id.to_s, :hk_public_holiday => {}
        assigns(:hk_public_holiday).should eq(hk_public_holiday)
      end

      it "re-renders the 'edit' template" do
        hk_public_holiday = HkPublicHoliday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HkPublicHoliday.any_instance.stub(:save).and_return(false)
        put :update, :id => hk_public_holiday.id.to_s, :hk_public_holiday => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hk_public_holiday" do
      hk_public_holiday = HkPublicHoliday.create! valid_attributes
      expect {
        delete :destroy, :id => hk_public_holiday.id.to_s
      }.to change(HkPublicHoliday, :count).by(-1)
    end

    it "redirects to the hk_public_holidays list" do
      hk_public_holiday = HkPublicHoliday.create! valid_attributes
      delete :destroy, :id => hk_public_holiday.id.to_s
      response.should redirect_to(hk_public_holidays_url)
    end
  end

end
